disks_num: 6
data_disks_num: 4
parity_disks_num: 2
group_size: 8192
# block_size: 4
data_dir: "data/"
test_dir: "data/testlog"

random_data_size: 1024

mode: 1 #real data mode = 1, synthetic random data mode = 0
real_file_name: "NTU_Logo.png"
is_save_rebuild: True
